language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install: 
  - sudo apt-get update -qq
  - sudo apt-get install libhdf5-serial-dev python-numpy python-scipy libatlas-dev liblapack-dev gfortran python-tk python-matplotlib hdf5-tools python-tables cython
# command to install dependencies
install:
  - "python setup.py install"
# command to run tests
script: nosetests -P
