language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install: 
  - sudo apt-get update -qq
  - sudo apt-get install libhdf5-serial-dev python-numpy python-scipy libatlas-dev liblapack-dev gfortran python-tk python-matplotlib
# command to install dependencies
install:
  - "pip install numexpr cython --use-mirrors"
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install ."
# command to run tests
script: nosetests -P
